spring.application.name=TTT-backend

spring.datasource.url=jdbc:postgresql://game-postgres:5432/ttt
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create

logging.level.sql=DEBUG
logging.level.web=DEBUG

ai.service.url=http://34.79.40.150/ai-player/move

launcher.api.url=http://localhost:8080

game.title=Tic tac toe from publish
game.description=tinker tanker toe
game.imageUrl=
game.gameUrl=http://localhost:5174/ttt/
game.price=23.5
game.genre=STRATEGY
game.maxlobbysize=2