spring.application.name=TTT-backend

spring.datasource.url=jdbc:postgresql://localhost:5444/ttt
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create

